name: k8sdeployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy keycloak
        run: ./kustomize build .k8s/overlays/staging/
