name: k8sdeployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject secrets
        run: |
          cd .k8s/base
          kustomize edit add secret shared-secret \
            --from-literal=postgres.username=${{ secrets.POSTGRES_USERNAME }} \
            --from-literal=postgres.password=${{ secrets.POSTGRES_PASSWORD }}
      - name: Deploy keycloak
        run: kustomize build .k8s/overlays/staging/
